name: CI Prod

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  pr-validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: SthoreH/shd-github-actions-workflows/actions/validate-pr@v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          validate-title: "true"
          validate-description: "false"

  ci:
    name: Validate Infra
    uses: SthoreH/shd-github-actions-workflows/.github/workflows/ci-infra-terraform.yml@v1.6.0
    with:
      environment: prod
    secrets: inherit
